name: Notification Service

# 监听 repository_dispatch 事件
on:
  repository_dispatch:
    types: [send-notification]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Send notification
      env:
        # Bark 通知配置
        BARK_URL: ${{ secrets.BARK_URL }}
        BARK_KEY: ${{ secrets.BARK_KEY }}
        
        # 钉钉通知配置
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
        
        # 飞书通知配置
        FSKEY: ${{ secrets.FSKEY }}
        
        # 企业微信通知配置
        QYWX_KEY: ${{ secrets.QYWX_KEY }}
        
        # Telegram 通知配置
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        
        # Server酱通知配置
        SCKEY: ${{ secrets.SCKEY }}
        SENDKEY: ${{ secrets.SENDKEY }}
        
        # SMTP 邮件通知配置
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_TO: ${{ secrets.SMTP_TO }}
        
        # Push+ 通知配置
        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        
        # Qmsg 通知配置
        QMSG_KEY: ${{ secrets.QMSG_KEY }}
        QMSG_QQ: ${{ secrets.QMSG_QQ }}
        
        # Gotify 通知配置
        GOTIFY_URL: ${{ secrets.GOTIFY_URL }}
        GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
        
        # GitHub Actions 事件相关环境变量
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        
      run: |
        echo "开始处理通知请求..."
        echo "事件类型: ${{ github.event.action }}"
        echo "事件数据: ${{ toJson(github.event.client_payload) }}"
        
        # 运行通知服务
        python main.py
        
    - name: Log notification result
      if: always()
      run: |
        echo "通知服务执行完成"
        echo "时间: $(date)"
        echo "事件来源: ${{ github.event.client_payload.source || 'unknown' }}"